// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function LoadConfig():Promise<main.AppConfig>;

export function SaveConfig(arg1:number):Promise<void>;

export function SessionCancelled():Promise<void>;

export function SessionComplete():Promise<void>;
